---
# Install dependencies on the host
#- name: Install pip
#  become: yes
#  apt:
#    name: ['python-pip']
#    state: latest
#    update_cache: yes
#  when: ansible_distribution == "Ubuntu"
# sudo apt-get update; sudo apt-get install python-pip

#- name: Update pip
#  become: no
#  pip:
#    name: ['pip']
#    state: latest
# pip install --upgrade pip

- name: Install openstacksdk
  become: no
  pip:
    name: ['openstacksdk']
    state: latest
    extra_args: --user
# pip install -U --user openstacksdk